"""empty message

Revision ID: 045646a6d199
Revises: 
Create Date: 2018-07-29 02:31:43.171916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '045646a6d199'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('_password', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=20), nullable=False),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
