"""empty message

Revision ID: 28e339853017
Revises: f40331a1ce4d
Create Date: 2018-08-21 17:21:53.193793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28e339853017'
down_revision = 'f40331a1ce4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project', sa.String(length=20), nullable=False),
    sa.Column('projectdescription', sa.String(length=100), nullable=True),
    sa.Column('creator', sa.String(length=20), nullable=False),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    # ### end Alembic commands ###
