"""empty message

Revision ID: 3386e8c2eed0
Revises: 93e7a515fb9d
Create Date: 2018-08-07 22:23:12.579610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3386e8c2eed0'
down_revision = '93e7a515fb9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('departmentname', sa.String(length=20), nullable=False),
    sa.Column('departmentdescription', sa.String(length=100), nullable=True),
    sa.Column('creator', sa.String(length=20), nullable=False),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('departmentname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
